### ISSUE TITLE
Clarify role of ID provider in business context

### ISSUE THREAD

**Issue by nuest** [o2r-project/architecture#4]
[this came out of discussion with publisher senior architect]

Update business context to clarify role of ID provider. Right now there is a mix-up between _authentication vs. authorization_ and between _envisioned architecture vs. technical details_ of the reference implementation.

## Tasks

- [ ] update graphic: user authenticates on the publication platform, which uses ID provider
- [ ] ~~make sure that the graphic also works with the case that the repro service is _only in the backend_~~ the reproducibility service is always just in the backend
- [ ] briefly describe how a OpenID Connect could be utilized here, 
    https://security.stackexchange.com/questions/44611/difference-between-oauth-openid-and-openid-connect-in-very-simple-term
